### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by dariovinci**
update to allow laravel 9.0 release

### CODE REVIEW

**Comment by codedge** [comment]
Would be nice to get this added @betterapp

**Comment by codedge** [comment]
Since 8.x and definitely in 9 this is not needed anymore as Laravel has a cast for encrypted values.

https://laravel.com/docs/9.x/eloquent-mutators#encrypted-casting

**Comment by seifti** [comment]
> Since 8.x and definitely in 9 this is not needed anymore as Laravel has a cast for encrypted values.
> 
> https://laravel.com/docs/9.x/eloquent-mutators#encrypted-casting

Right now I say which columns I want to encrypt by setting it as an array in the model (with betterapp's library) - how would you do that with https://laravel.com/docs/9.x/eloquent-mutators#encrypted-casting ? Do you have any example?

I tried adding:
`$casts = ['column1' => 'encrypted']`

But when it decrypts, it return the value with this format: `s:23:"Harry Potter";` instead of `Harry Potter`

**Comment by seifti** [comment]
@rytisder @safly @vladkucherov @moebrowne can any of you approve this one?

**Review by lukebouch — APPROVED** [review]

**Comment by lukebouch** [comment]
@seifti I approved it.

**Pull request closed without merging**
